C MSJUNK.H - INTERFACE DATA REQUIRED BY MICROSOFT POWERSTATION FORTRAN
C THIS CORRECTS A REALLY STUPID MICROSOFT EXTENSION TO FORTRAN

      INTERFACE

      SUBROUTINE DEFBLK (I1,I2,I3,C4,I5,I6)
      CHARACTER*(*) C4
      !MS$ATTRIBUTES REFERENCE :: C4
      !MS$ATTRIBUTES STDCALL, REFERENCE :: DEFBLK
      END SUBROUTINE DEFBLK

      SUBROUTINE DEFGRD (I1,I2,I3,I4,I5,I6,I7,I8,I9)
      INTEGER*2 I8(*)
      INTEGER*4 I6(*),I7(*)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: DEFGRD
      END SUBROUTINE DEFGRD

      SUBROUTINE BLKDIM (I1,I2,I3,I4,I5)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: BLKDIM
      END SUBROUTINE BLKDIM

      SUBROUTINE BLKOFF (I1,I2,I3,I4,I5)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: BLKOFF
      END SUBROUTINE BLKOFF

      SUBROUTINE BLKNAME (I1,C2,I3)
      CHARACTER*(*) C2
      !MS$ATTRIBUTES REFERENCE :: C2
      !MS$ATTRIBUTES STDCALL, REFERENCE :: BLKNAME
      END SUBROUTINE BLKNAME

      SUBROUTINE ALCGEA (C1,I2,I3,I4,I5)
      CHARACTER*(*) C1
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ALCGEA
      END SUBROUTINE ALCGEA

      SUBROUTINE PNTVAR (I1,I2,I3)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: PNTVAR
      !MS$ATTRIBUTES REFERENCE :: I1,I2,I3
      END SUBROUTINE PNTVAR

      SUBROUTINE PNTVARR8 (R8,I2,I3)
      REAL*8 R8
      !MS$ATTRIBUTES REFERENCE :: R8,I2,I3
      !MS$ATTRIBUTES STDCALL, REFERENCE :: PNTVARR8
      END SUBROUTINE PNTVARR8

      SUBROUTINE PNTVARR4 (R4,I2,I3)
      REAL*4 R4
      !MS$ATTRIBUTES REFERENCE :: R4,I2,I3
      !MS$ATTRIBUTES STDCALL, REFERENCE :: PNTVARR4
      END SUBROUTINE PNTVARR4

      SUBROUTINE ARYDAT (C1,I2,I3,I4,I5)
      CHARACTER*(*) C1(*)
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ARYDAT
      END SUBROUTINE ARYDAT

      SUBROUTINE ARYTYPE (I1,I2,I3,I4,I5)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ARYTYPE
      END SUBROUTINE ARYTYPE

      SUBROUTINE RALCGEA (I1,I2,I3,I4,I5,I6,I7,I8)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: RALCGEA
      END SUBROUTINE RALCGEA

      SUBROUTINE FREARY (I1)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: FREARY
      END SUBROUTINE FREARY

      SUBROUTINE FREEALL ()
      !MS$ATTRIBUTES STDCALL, REFERENCE :: FREEALL
      END SUBROUTINE FREEALL

      SUBROUTINE KILARY ()
      !MS$ATTRIBUTES STDCALL, REFERENCE :: KILARY
      END SUBROUTINE KILARY

      SUBROUTINE CALLWORK (E,I)
      EXTERNAL E
      INTEGER*4 I(*)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: CALLWORK
      END SUBROUTINE CALLWORK

      SUBROUTINE EXTDEF (R1,I1,C1,I2,I3,I4,I5)
      REAL*8 R1
      CHARACTER*(*) C1
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTDEF
      END SUBROUTINE EXTDEF

      SUBROUTINE EXTNUM (C1,I1,I2,I3,I4)
      CHARACTER*(*) C1
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTNUM
      END SUBROUTINE EXTNUM

      SUBROUTINE EXTGET (R1,I1,I2,I3,I4,I5)
      REAL*8 R1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTGET
      END SUBROUTINE EXTGET

      SUBROUTINE EXTPUT (R1,I1,I2,I3,I4,I5)
      REAL*8 R1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTPUT
      END SUBROUTINE EXTPUT

      SUBROUTINE EXTDEL (I1,I2)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTDEL
      END SUBROUTINE EXTDEL

      SUBROUTINE CLEAREV ()
      !MS$ATTRIBUTES STDCALL, REFERENCE :: CLEAREV
      END SUBROUTINE CLEAREV

      SUBROUTINE EXTNAM (I1,C1)
      CHARACTER*(*) C1(*)
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: EXTNAM
      END SUBROUTINE EXTNAM

      SUBROUTINE GEAOUT (I1,I2,I3)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: GEAOUT
      END SUBROUTINE GEAOUT

      SUBROUTINE ALLBLOCKS()
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ALLBLOCKS
      END SUBROUTINE ALLBLOCKS

      SUBROUTINE GETANAM(I1,C1,I2)
      CHARACTER*(*) C1(*)
      !MS$ATTRIBUTES REFERENCE :: C1
      !MS$ATTRIBUTES STDCALL, REFERENCE :: GETANAM
      END SUBROUTINE GETANAM

      SUBROUTINE CALLFACE(I1,I2,I3)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: CALLFACE
      END SUBROUTINE CALLFACE

      SUBROUTINE ALCIBUF(I1,I2,I3,I4)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ALCIBUF
      END SUBROUTINE ALCIBUF

      SUBROUTINE PNTMMOD(I1,I2)
      INTEGER*4 I2(*)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: PNTMMOD
      END SUBROUTINE PNTMMOD

      SUBROUTINE ALCMGA(I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11)
      INTEGER*4 I2(*),I4(*),I5(*),I6(*),I7(*),I8(*),I9(*)
      !MS$ATTRIBUTES STDCALL, REFERENCE :: ALCMGA
      END SUBROUTINE ALCMGA

      SUBROUTINE MGWORK1 (E,I1,I2,I3)
      EXTERNAL E
      !MS$ATTRIBUTES STDCALL, REFERENCE :: MGWORK1
      END SUBROUTINE MGWORK1

      SUBROUTINE MGWORK2 (E,I1)
      EXTERNAL E
      !MS$ATTRIBUTES STDCALL, REFERENCE :: MGWORK2
      END SUBROUTINE MGWORK2

      SUBROUTINE MGWORK3 (E,I1)
      EXTERNAL E
      !MS$ATTRIBUTES STDCALL, REFERENCE :: MGWORK3
      END SUBROUTINE MGWORK3

      SUBROUTINE MGWORK4 (E,I1,I2,I3)
      EXTERNAL E
      !MS$ATTRIBUTES STDCALL, REFERENCE :: MGWORK4
      END SUBROUTINE MGWORK4

      END INTERFACE
