C  ROCKPG.H - DATA FOR USER PROGRAM 

      COMMON /ROCKPG/ RNBLK,X,Y,Z,DEP,PORP,XPERMP,YPERMP,ZPERMP,
     &   NPGD,NPGR,KE,HDEPMOD,HPORMOD,HXPRMOD,HYPRMOD,HZPRMOD

      REAL*8 RNBLK,X,Y,Z,DEP,PORP,XPERMP,YPERMP,ZPERMP
      LOGICAL HDEPMOD,HPORMOD,HXPRMOD,HYPRMOD,HZPRMOD

C*********************************************************************

C  RNBLK   = PROGRAM EXTERNAL VARIABLES     BLOCK NUMBER
C  X,Y,Z                                    LOCATION
C  DEP                                      DEPTH
C  PORP                                     POROSITY
C  XPERMP                                   PERMEABILITIES
C  YPERMP
C  ZPERMP

C  NPGD = DEPTHMOD PROGRAM NUMBER

C  NPGR = ROCKMOD PROGRAM NUMBER

C  KE   = PROGRAM ERROR NUMBER

C  HDEPMOD = FLAG INDICATING DEPTHMOD PROGRAM WAS INPUT

C  HPORMOD = FLAG INDICATING POROSITY WAS MODIFIED
C  HXPRMOD = FLAG INDICATING X PERMEABILITY WAS MODIFIED
C  HYPRMOD = FLAG INDICATING Y PERMEABILITY WAS MODIFIED
C  HZPRMOD = FLAG INDICATING Z PERMEABILITY WAS MODIFIED
