C  SCRAT2.H - TEMPORARY WORK AREA FOR TABLE.FOR

      REAL*8    W,BB,BBB,BCF,DATS,SCOF,SCONS,SNOD,FACMU,FACAU
      LOGICAL ISUNT
      CHARACTER*60 UNTS,UNTI
      COMMON /SCRAT2/ W(20,21), BB(20), BBB(20), BCF(20), DATS(200),
     & SCOF(4,19), SCONS(4,6), SNOD(18), FACMU(3), FACAU(3), ISUNT(3),
     & BSTEP(20),UNTS(3), UNTI(3)
