C  TIMES.H - TIMER DATA

      COMMON /TIMESD/TIMTOT(50),TIMIN(50),NUMTIM,ALLTIMES,
     & TIMKLS(50),TIMRUN(50),TIMNAM(50)

      REAL*8 TIMTOT,TIMIN
      INTEGER NUMTIM,TIMKLS
      CHARACTER*40 TIMNAM
      LOGICAL TIMRUN,ALLTIMES

C*********************************************************************

C  TIMTOT() = TIME ACCUMILATED IN SECONDS

C  TIMIN()  = TIME WHEN TIMER IS STARTED OR RESTARTED, SECONDS

C  NUMTIM = TOTAL NUMBER OF TIMERS

C  TIMKLS(I) = TIMER CLASS
C            = 0 ==> UNUSED
C            = 1 ==> TOTAL TIME
C            = 2 ==> ALL COMMUNICATION TIMES INCLUDING WAIT TIME
C            = 3 ==> ALL REDUNDANT CALCULATION TIMES
C            = 4 ==> MISCELLENOUS TIMES

C  TIMRUN() = TRUE IF TIMER IS RUNNING

C  TIMNAM() = TIMER NAMES

C  ALLTIMES = FLAG TO PRINT ALL MULTIPROCESSOR TIMES
