C  UTLDAT.H - 1D TABLE DATA

      REAL*8 TABX,TABY,DYDX,TRANC1,VALUES,XYZERO
      INTEGER NTBU,NEXFRE,INTRPS,KXTRPS,INDEX1,INDEX2,INDEXL,KTRANS
      LOGICAL ISUNTDT
C
      COMMON /TABLES/ TABX,TABY,DYDX,TRANC1(76),VALUES(2000),
     & XYZERO(76),NTBU,NEXFRE,ISUNTDT,INTRPS(76),KXTRPS(76),
     & INDEX1(76),INDEX2(76),INDEXL(76),KTRANS(76)
