C  VISTABC.H - COMMON FOR TECPLOT TABLE OUTPUT

C  HISTORY:

C  JOHN WHEELER      12/30/99     ORIGINAL BETA CODE

C*********************************************************************

      COMMON /VISTABC/ TECPLT,TECLAY,HAVBAS,NFTABPLT,NFTABLAY,
     & NFTABBAS,NFPPG,NPLOTS,
     & TPPLT,TPBASE,TPLAY

      LOGICAL TECPLT,TECLAY
      CHARACTER*50 TPPLT,TPBASE,TPLAY

C*********************************************************************

C  TECPLT = TECPLOT PLOT OUTPUT CONTROL (.TRUE. ==> DO IT)

C  TECLAY = TECPLOT LAYOUT OUTPUT CONTROL (.TRUE. ==> DO IT)

C  NFTABBAS = FILE NUMBER FOR TECPLOT LAYOUT INPUT

C  NFTABPLT = FILE NUMBERS FOR TECPLOT PLOT DATA AND LAYOUT OUTPUT
C  NFTABLAY

C  TPPLT = FILE NAMES FOR TECPLOT PLOT, LAYOUT INPUT. AND LAYOUT OUTPUT FILES
C  TPBASE 
C  TPLAY

C  NFPPG = NUMBER OF FRAMES PER PAGE

C  NPLOTS = NUMBER OF FRAMES OUTPUT
