C  TRARYDAT.H - TRANSPORT-CHEMISTRY MODEL GRID-ELEMENT ARRAY NUMBERS

C  CODE HISTORY:

C M. PESZYNSKA, 8/00, INITIAL VERSION
C*********************************************************************

      INTEGER   N_TRVX, N_TRVY, N_TRVZ, N_CONC,  N_CONCARR($MXNSPEC)
     &     ,N_CONCN,N_CONCR
     &     ,N_CONCOLD, N_PHIS, N_PHISN, N_PHISN2, N_SATU, N_SATUN
     &     ,N_TRVEL, N_TRVELN, N_TRVELN2, N_TRCOF, N_TRDUNK, N_TRRESID
     &     ,N_DISP, N_DISPARR(9), N_TRSLP

      COMMON /TRCOMBL/ 
     &     N_TRVX, N_TRVY, N_TRVZ, N_CONC, N_CONCARR, N_CONCOLD
     &    ,N_CONCN,N_CONCR
     &    ,N_PHIS, N_PHISN, N_PHISN2, N_SATU, N_SATUN, N_TRVEL
     &    ,N_TRVELN, N_TRVELN2, N_TRSLP

      COMMON /TRDIFF/
     &     N_TRCOF, N_TRDUNK, N_TRRESID
     &    ,N_DISP, N_DISPARR

C*********************************************************************

C  N_TRVX, N_TRVY, N_TRVZ - VELOCITY VECTOR [FT/DAY]

C  N_CONC         - CONCENTRATION IN FLOWING PHASES FOR ALL SPECIES,
C                          LBMOL/(FT^3 OF PHASE)
C
C  N_CONCN         - CONCENTRATION IN FLOWING PHASES FOR ALL SPECIES 
C                   AT PREVIEOUS TIMESTEP,
C                          LBMOL/(FT^3 OF PHASE)
C  N_CONCR         - CONCENTRATION IN FLOWING PHASES FOR ALL SPECIES 
C                   AFTER REACTION,
C                          LBMOL/(FT^3 OF PHASE)
C  N_CONCARR(L)   - CONCENTRATION IN FLOWING PHASES FOR SPECIES L,
C                          LBMOL/(FT^3 OF PHASE)
C        NOTE: N_CONC AND N_CONCARR(1) POINT TO THE SAME MEMORY

C  N_CONCOLD      - CONCENTRATION IN FLOWING PHASES, LBMOL/(FT^3 OF PHASE) 
C                            (PREVIOUS TIME STEP)

C  N_PHIS         - PHASE WEIGHTED CAPACITY (DENOTED PHIS GIVEN BY:
C                   PHIS = POROSITY * 
C                        [\SUM_PHASES (GAMMA(PHASE,SPECIES)*SAT(PHASE)) 
C                       + GAMMA(ROCK,SPECIES)]
C THESE DEFINITIONS APPLY TO N_PHIS,N_PHISN,N_PHISN2 WHICH ARE COMPUTED,
C RESPECTIVELY : AFTER FLOW STEP (T_N+1), BEFORE T_N AND AS INTERPOLATION
C OF THE ABOVE TWO, AT T_N+1/2)

C N_TRCOF, N_TRDUNK, N_TRRESID 
C -- NOTICE THAT WE CANNOT USE N_COF, N_DUNK, N_RESID AS OUR VARIABLES 
C    BECAUSE THAT WILL HAVE CONFLICTION WITH FLOW MODEL

C   N_DISP        -- DISPERSION/DIFFUSION TENSOR  [UNIT: FT^5/DAY]
C   N_DISPARR     -- DISPERSION/DIFFUSION TENSOR INDIVIUALLY FOR EACH IJ
C                      [UNIT: FT^5/DAY]
C                    N_DISPARR(1) -- DISPERSION_XX
C                    N_DISPARR(2) -- DISPERSION_XY
C                    N_DISPARR(3) -- DISPERSION_XZ
C                    N_DISPARR(4) -- DISPERSION_YX
C                    N_DISPARR(5) -- DISPERSION_YY
C                    N_DISPARR(6) -- DISPERSION_YZ
C                    N_DISPARR(7) -- DISPERSION_ZX
C                    N_DISPARR(8) -- DISPERSION_ZY
C                    N_DISPARR(9) -- DISPERSION_ZZ

C N_TRSLP         - ELEMENT "SLOPES" OF SCALAR VARIABLE IN ADVECTION 
C                   EQUATION, USED FOR FLUX RECONSTRUCTION IN HIGHER 
C                   ORDER GODUNOV METHOD.
