C  BLKARY.H - GRID-BLOCK ARRAYS USED BY ALL MODELS

      INTEGER I4UTIL,N_XC,N_YC,N_ZC,N_ROCK,N_POR,N_DEPTH,
     & N_TCOFX,N_TCOFY,N_TCOFZ,N_R8U,N_R4U,N_I4U,N_KTU,
     & N_XPERM,N_YPERM,N_ZPERM,N_KPU,KTU,KPU,
     & N_BC_TYPE(3)
      REAL*4 R4UTIL
      REAL*8 R8UTIL
      CHARACTER*50 TITU

      COMMON /BLKARY/R8UTIL,R4UTIL,I4UTIL,
     & N_XC,N_YC,N_ZC,N_ROCK,N_POR,N_DEPTH,N_TCOFX,N_TCOFY,N_TCOFZ,
     & N_XPERM,N_YPERM,N_ZPERM,N_R8U,N_R4U,N_I4U,N_KTU,N_KPU,
     & N_BC_TYPE,
     & KTU,KPU,TITU

C*****************  ARRAYS FOR ALL MODELS

C  N_XC, N_YC, N_ZC = GRID BLOCK CORNER ARRAY NUMBERS (FT,REAL*4)
C                     VALID ONLY FOR KNDGRD = 2

C  N_ROCK = ARRAY NUMBER FOR ROCK TYPE OF GRID ELEMENTS

C  N_POR = ARRAY NUMBER FOR POROSITY OF GRID ELEMENTS (REAL*4)

C  N_DEPTH = ARRAY NUMBER FOR BLOCK CENTER DEPTH (FT,REAL*8)

C  N_TCOFX = ARRAY NUMBERS FOR TRANSMISSABILITY COEFFICIENT CONSTANT
C  N_TCOFY   FACTORS (REAL*8)
C  N_TCOFZ

C  N_XPERM = PERMEABILITIES (md,REAL*4)
C  N_YPERM
C  N_ZPERM

C*****************  UTILITY VARIABLES FOR ARRAY OPERATIONS

C  N_R8U, N_R4U, N_I4U = ARRAY NUMBERS FOR R8UTIL, R4UTIL, AND I4UTIL

C  R8UTIL = UTILITY VARIABLE (REAL*8)

C  R4UTIL = UTILITY VARIABLE (REAL*4)

C  I4UTIL = UTILITY VARIABLE (INTEGER)

C  N_KTU, N_KPU = ARRAY NUMBERS FOR KTU AND KPU

C  KTU = UTILITY VARIABLE TYPE FOR PRINTING GRID-BLOCK ARRAYS

C  KPU = UTILITY CENTER/CORNER KEY FOR PRINTING GRID-BLOCK ARRAYS

C  TITU = UTILITY TITLE FOR PRINTING GRID-BLOCK ARRAYS (CHARACTER*50)
C         USED BY GEAOUT

C  N_BC_TYPE = BOUNDARY-ELEMENT ARRAY NUMBER FOR BOUNDARY TYPE, (INTEGER)
C              0: NO-FLOW BOUNDARY CONDITION, 1: PRESSURE SPECIFIED
C              BOUNDARY CONDITION.
C              THREE VALUES FOR X, Y, Z DIRECTION RESPECTIVELY.
