C  HFLUIDS.H - HYDROLOGY MODEL FLUID PROPERTIES

C  CODE HISTORY:

C  JOHN WHEELER     4/29/97    MODIFY PIERS INCLUDE FILE

C*********************************************************************
      REAL*4 OILCMP,   OILDEN,   WATCMP,   WATDEN,
     &       DENWR,    OILVIS,   WATVIS,   RDENOR,   DRATIO,   POINIT,
     &       PWINIT,   SWINIT,   DINIT
      INTEGER KRKI

      COMMON /HFLUIDS/  OILCMP,   OILDEN,   WATCMP,   WATDEN,
     &       DENWR,    OILVIS,   WATVIS,   RDENOR,   DRATIO,   POINIT,
     &       PWINIT,   SWINIT,   DINIT,    KRKI

      LOGICAL HREADIN
      COMMON /HREADIN/ HREADIN

C*********************************************************************
 
C  OILCMP = OIL COMPRESSABILITY, 1/psi

C  OILDEN = OIL DENSITY AT 0 PRESSURE, lb/cu-ft

C  WATCMP = WATER COMPRESSABILITY, 1/psi

C  WATDEN = WATER DENSITY AT 0 PRESSURE, lb/cu-ft

C  DENWR  = NOMINAL WATER DENSITY AT RESERVOIR CONDITIONS, lb/cu-ft

C  OILVIS = OIL VISCOSITY, cp

C  WATVIS = WATER VISCOSITY, cp

C  RDENOR = RECRIPROCAL OF OIL DENSITY AT REFERENCE DEPTH, lb/cu-ft

C  DRATIO = RATIO OF WATER DENSITY TO OIL DENSITY AT REFERENCE DEPTH, lb/cu-ft

C  POINIT = INITIAL OIL PRESSURE AT REFERENCE DEPTH, psi
C  PWINIT = INITIAL WATER PRESSURE AT REFERENCE DEPTH, psi
C           ONLY ONE OF THESE PRESSURES MAY BE SPECIFIED

C  SWINIT = INITIAL WATER SATURATION AT REFERENCE DEPTH

C  DINIT  = INITIAL REFERENCE DEPTH, ft

C  KRKI   = INITIAL REFERENCE ROCK TYPE
