c  TARYDAT.H - IMPLICIT SINGLE PHASE FLOW MODEL GRID-ELEMENT ARRAY NUMBERS

C  CODE HISTORY:

C  BAHAREH MOMKEN  02/02/99   Hydrology-IMPES model garydat.h is used
C                             as template
C  JOHN WHEELER    04/03/99   IMPLICIT SINGLE PHASE MODEL

C*********************************************************************

      INTEGER N_PRES, N_FLDEN, N_PRESN, N_FLDENN, N_DUNK,
     &   N_COF,N_RESID,N_VEL,N_PRES_ERR,
     &   N_AINVF,N_UPMOBPROD,
     &   N_CR, N_PV, N_PVN, N_REFPRES, N_DELTAP,
ctm   TAMEEM
     &   N_FLDEN3, N_PRESN3, N_PVN3, N_PRESN_N1, N_PRESN_NM1,
ctm   TAMEEM
     &   N_MODULFLOW, N_POISSFLOW, N_BIOTAFLOW
     
      COMMON /TBAH/ N_PRES,N_FLDEN, N_PRESN, N_FLDENN, N_DUNK,
     &   N_COF,N_RESID,N_VEL,N_PRES_ERR,
     &   N_AINVF,N_UPMOBPROD,
     &   N_CR, N_PV, N_PVN, N_REFPRES, N_DELTAP,
ctm   TAMEEM
     &   N_FLDEN3, N_PRESN3, N_PVN3, N_PRESN_N1, N_PRESN_NM1,
ctm   TAMEEM
     &   N_MODULFLOW, N_POISSFLOW, N_BIOTAFLOW
   
C*********************************************************************

C  N_PRES = GRID-ELEMENT ARRAY NUMBER FOR FLUID PRESSURE AT TIME N+1,
C           PSI (REAL*8)

C  N_PRESN = GRID-ELEMENT ARRAY NUMBER FOR FLUID PRESSURE AT TIME N,
C            PSI (REAL*8)

C  N_FLDEN = GRID-ELEMENT ARRAY NUMBER FOR FLUID DENSITY AT TIME N+1,
C            LB/CU-FT (REAL*8)

C  N_FLDENN = GRID-ELEMENT ARRAY NUMBER FOR FLUID DENSITY AT TIME N,
C             LB/CU-FT (REAL*8)

C  N_COF (called COF below):
C      = GRID-ELEMENT ARRAY NUMBER FOR MATRIX COEFFICIENTS (REAL*8)
C        27 POINT TEMPLATE ($NUMCOF=27)

C  N_RESID= GRID-ELEMENT ARRAY NUMBER FOR RESIDUALS (REAL*8)

C  N_DUNK = GRID-ELEMENT ARRAY NUMBER FOR PRESSURE CHANGE (REAL*8)

C  N_CR = GRID-ELEMENT ARRAY NUMBER FOR ROCK COMPRESSIBILITY (REAL*8)

C  N_AINVF = A^(-1)*F, F = GRAVITY + CAPILLARY PRESSURE + BC (REAL*8)

C  N_UPMOBPROD = UPWINDED MOBILITY PRODUCT, CONTAINS AVERAGE DENSITY AT FACES

C  N_CR = ROCK COMPRESSIBILITY (1/PSI)

C  N_PV = PORE VOLUME AT CURRENT TIME (CU-FT)

C  N_PVN = PORE VOLUME AT PREVIOUS TIME (CU-FT)

C  N_REFPRES = REFERENCE PRESSURE (PSI)

C  N_PRES_ERR = GRID-ELEMENT ARRAY NUMBER FOR ERROR IN FLUID PRESSURE 
C               AGAINST ANALYTIC SOLUTION AT TIME N+1,
C           PSI (REAL*8)

