C  HARYDAT.H - HYDROLOGY MODEL GRID-ELEMENT ARRAY NUMBERS

C  CODE HISTORY:

C  JOHN WHEELER     4/29/97    ALPHA VERSION
C  JOHN WHEELER     8/29/98    MODULAR VERSION
C  GURPREET SINGH   11/11/15   TWO PHASE IMPLICIT MFMFE

C*********************************************************************
      INTEGER N_POIL,N_PWAT,N_COIL,N_DUNK,N_COILN,N_CWATN,
     &     N_RELPRM,N_DPCSW,N_COF,N_HCOF,N_RESID,N_HRESID,N_POILN,
     &     N_HVEL,N_VMO,N_VMW,N_DDENS,N_CR,N_PV,N_PVN,N_REFPRES,
     &     N_AINVF,N_UPMOBPROD,N_UPMOB,N_CWAT,N_DELC,N_HDUNK

      COMMON /HGEA/ N_POIL,N_PWAT,N_COIL,N_DUNK,N_COILN,N_CWATN,
     &     N_RELPRM,N_DPCSW,N_COF,N_HCOF,N_RESID,N_HRESID,N_POILN,
     &     N_HVEL,N_VMO,N_VMW,N_DDENS,N_CR,N_PV,N_PVN,N_REFPRES,
     &     N_AINVF,N_UPMOBPROD,N_UPMOB,N_CWAT,N_DELC,N_HDUNK

C*********************************************************************

C  N_POIL = GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE, PSI (REAL*8)

C  N_PWAT = GRID-ELEMENT ARRAY NUMBER FOR WATER PRESSURE, PSI (REAL*8)

C  N_COIL = GRID-ELEMENT ARRAY NUMBER FOR OIL CONCENTRATION, LB/CU-FT (REAL*8)

C  N_CWAT = GRID-ELEMENT ARRAY NUMBER FOR WATER CONCENTRATION, LB/CU-FT (REAL*8)

C  N_DUNK  = GRID-ELEMENT ARRAY NUMBER FOR LINEAR SOLUTION
C           DUNK(I,J,K,1)

C  N_HDUNK  = GRID-ELEMENT ARRAY NUMBER FOR LINEAR SOLUTION
C           DUNK(I,J,K)

C  N_COILN = GRID-ELEMENT ARRAY NUMBER FOR OIL CONCENTRATION AT BEGINNING
C            OF TIME STEP , LB/CU-FT (REAL*8)

C  N_CWATN = GRID-ELEMENT ARRAY NUMBER FOR WATER CONCENTRATION AT BEGINNING
C            OF TIME STEP , LB/CU-FT (REAL*8)

C  N_RELPRM = GRID-ELEMENT ARRAY NUMBER FOR RELATIVE PERMEABILITY DATA
C             (REAL*8)
C             RELPRM(I,J,K,1) = OIL RELATIVE PERMEABILITY
C             RELPRM(I,J,K,2) = DERIVATIVE OIL RELATIVE PERMEABILITY WRT Sw
C             RELPRM(I,J,K,3) = WATER RELATIVE PERMEABILITY
C             RELPRM(I,J,K,4) = DERIVATIVE WATER RELATIVE PERMEABILITY WRT Sw

C  N_DPCSW  = GRID-ELEMENT ARRAY NUMBER FOR DERIVATIVE OF Pc WRT Sw, PSI
C             (REAL*8)

C  N_HCOF  = GRID-ELEMENT ARRAY NUMBER FOR JACOBIAN COEFFICIENTS (REAL*8)
C           COF(I,J,K,N,L)
C           L=1 ==> OIL BALANCE EQUATION
C           L=2 ==> WATER BALANCE EQUATION
C           27 POINT TEMPLATE ($NUMCOF=27)

C  N_HRESID= GRID-ELEMENT ARRAY NUMBER FOR RESIDUALS (REAL*8)
C           RESID(I,J,K,N) ==> RESIDUAL OF EQUATION N
C           N=1 ==> OIL BALANCE EQUATION
C           N=2 ==> WATER BALANCE EQUATION

C  N_POILN = GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE AT BEGINNING OF
C            TIME STEP , PSI (REAL*8)

C  N_CR    = GRID-ELEMENT ARRAY NUMBER FOR ROCK COMPRESSIBILITY
C            CR(I,J,K) , 1/PSI (REAL*8)

C  N_PV    = GRID-ELEMENT ARRAY NUMBER FOR PORE VOLUME
C            PV(I,J,K) , CU-FT (REAL*8)

C  N_PVN    = GRID-ELEMENT ARRAY NUMBER FOR PORE VOLUME AT BEGINNING OF
C             TIME STEP, CU-FT (REAL*8)
C            PV(I,J,K) , CU-FT (REAL*8)

C  N_REFPRES= REFERENCE PRESSURE (PSI)
C

C  N_UPMOBPROD= UPWINDED PRODUCT OF PHASE MASS DENSITY AND
C               MOBILITY. CONSTANT FOR TIMESTEP.


C  N_UPMOB= UPWINDED MOBILITY. CONSTANT FOR TIMESTEP.
C

C  N_DELC = GRID-ELEMENT ARRAY NUMBER FOR CHANGE IN
C           PHASE CONCENTRATIONS
C           DELS(I,J,K,L), REAL*8
C           L = 1 ==> OIL SATURATION
C           L = 2 ==> WATER SATURATION
          
